import { useState } from "react"

const API_URL = "http://127.0.0.1:8000"

function Allocation({
  patients,
  rooms,
  setPatients,
  setRooms,
  allocationResult,
  setAllocationResult,
}) {
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState("")

  async function runAllocation() {
    setError("")
    setAllocationResult(null)

    if (patients.length === 0) {
      setError(
        "There are no patients waiting for allocation."
      )
      return
    }

    if (rooms.length === 0) {
      setError("No hospital resources are configured.")
      return
    }

    const availableRooms = rooms.filter(
      (room) => room.available
    )

    if (availableRooms.length === 0) {
      setError("No available hospital resources remain.")
      return
    }

    setLoading(true)

    try {
      const response = await fetch(`${API_URL}/allocate`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          patients,
          rooms,
        }),
      })

      if (!response.ok) {
        throw new Error(
          `Allocation request failed with status ${response.status}.`
        )
      }

      const data = await response.json()

      setAllocationResult(data)

      if (data.status === "allocated") {
        const allocatedRoomIds = new Set(
          Object.values(data.allocations)
        )

        const allocatedPatientIds = new Set(
          Object.keys(data.allocations)
        )

        // Mark allocated resources as occupied.
        setRooms((current) =>
          current.map((room) =>
            allocatedRoomIds.has(room.id)
              ? {
                  ...room,
                  available: false,
                }
              : room
          )
        )

        // Remove successfully allocated patients
        // from the waiting list.
        setPatients((current) =>
          current.filter(
            (patient) =>
              !allocatedPatientIds.has(patient.id)
          )
        )
      }
    } catch (requestError) {
      setError(
        requestError.message ||
          "Unable to connect to the allocation server."
      )
    } finally {
      setLoading(false)
    }
  }

  const isAllocated =
    allocationResult?.status === "allocated"

  const isConflict =
    allocationResult?.status === "conflict"

  return (
    <div className="mx-auto max-w-7xl">
      <div className="mb-8">
        <h2 className="text-2xl font-semibold">
          AI Allocation
        </h2>

        <p className="mt-1 text-sm text-slate-500">
          Run the CSP and backtracking engine to allocate
          patients to compatible hospital resources.
        </p>
      </div>

      <div className="grid gap-6 lg:grid-cols-[1fr_320px]">
        <section className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="font-semibold">
                Allocation Result
              </h3>

              <p className="mt-1 text-xs text-slate-500">
                Results generated by the backend CSP engine.
              </p>
            </div>

            {allocationResult && (
              <span
                className={`rounded-full px-3 py-1 text-xs font-medium ${
                  isAllocated
                    ? "bg-emerald-50 text-emerald-700"
                    : "bg-red-50 text-red-700"
                }`}
              >
                {isAllocated
                  ? "Allocation Successful"
                  : "Conflict Detected"}
              </span>
            )}
          </div>

          {error && (
            <div className="mt-6 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
              {error}
            </div>
          )}

          {!allocationResult && !error && (
            <div className="mt-8 rounded-lg border border-dashed border-slate-300 p-10 text-center">
              <p className="text-sm text-slate-500">
                Add fictional patients to the waiting list,
                then run AI allocation.
              </p>
            </div>
          )}

          {isAllocated && (
            <div className="mt-6">
              <h4 className="text-sm font-semibold">
                Patient → Resource Allocation
              </h4>

              <div className="mt-4 space-y-3">
                {Object.entries(
                  allocationResult.allocations
                ).map(([patientId, roomId]) => (
                  <div
                    key={patientId}
                    className="rounded-lg border border-slate-200 p-4"
                  >
                    <div className="flex items-center justify-between">
                      <div>
                        <p className="font-medium">
                          {patientId}
                        </p>

                        <p className="mt-1 text-sm text-slate-500">
                          Allocated to resource {roomId}
                        </p>
                      </div>

                      <span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-medium text-emerald-700">
                        Allocated
                      </span>
                    </div>

                    {allocationResult.explanations?.[
                      patientId
                    ] && (
                      <div className="mt-4 border-t border-slate-100 pt-3">
                        <p className="text-xs font-medium text-slate-500">
                          Why this allocation is valid
                        </p>

                        <ul className="mt-2 space-y-1">
                          {allocationResult.explanations[
                            patientId
                          ].map((reason) => (
                            <li
                              key={reason}
                              className="text-xs text-slate-600"
                            >
                              ✓ {reason}
                            </li>
                          ))}
                        </ul>
                      </div>
                    )}
                  </div>
                ))}
              </div>

              <div className="mt-5 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3">
                <p className="text-sm font-medium text-emerald-800">
                  Allocation completed successfully.
                </p>

                <p className="mt-1 text-xs text-emerald-700">
                  Allocated patients have been removed from
                  the waiting list and assigned resources are
                  now occupied.
                </p>
              </div>
            </div>
          )}

          {isConflict && (
            <div className="mt-6">
              <h4 className="text-sm font-semibold">
                Allocation Conflict
              </h4>

              <div className="mt-4 space-y-3">
                {allocationResult.conflicts?.map(
                  (conflict, index) => (
                    <div
                      key={`${conflict.patient_id}-${index}`}
                      className="rounded-lg border border-red-200 bg-red-50 p-4"
                    >
                      <p className="font-medium text-red-800">
                        Patient {conflict.patient_id}
                      </p>

                      <p className="mt-1 text-sm text-red-700">
                        {conflict.reason}
                      </p>

                      <p className="mt-2 text-xs text-red-600">
                        Constraint:{" "}
                        {conflict.constraint}
                      </p>
                    </div>
                  )
                )}
              </div>

              {allocationResult.unallocated?.length > 0 && (
                <div className="mt-5">
                  <p className="text-xs font-medium text-slate-500">
                    Unallocated patients
                  </p>

                  <div className="mt-2 flex flex-wrap gap-2">
                    {allocationResult.unallocated.map(
                      (patientId) => (
                        <span
                          key={patientId}
                          className="rounded-full bg-slate-100 px-3 py-1 text-xs text-slate-700"
                        >
                          {patientId}
                        </span>
                      )
                    )}
                  </div>
                </div>
              )}
            </div>
          )}
        </section>

        <aside className="h-fit rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
          <h3 className="font-semibold">
            Allocation Controls
          </h3>

          <p className="mt-1 text-xs text-slate-500">
            Current hospital resources available to the CSP
            engine.
          </p>

          <div className="mt-6 space-y-3">
            <div className="flex items-center justify-between rounded-lg bg-slate-50 p-3">
              <span className="text-sm text-slate-600">
                Waiting Patients
              </span>

              <span className="font-semibold">
                {patients.length}
              </span>
            </div>

            <div className="flex items-center justify-between rounded-lg bg-slate-50 p-3">
              <span className="text-sm text-slate-600">
                Total Resources
              </span>

              <span className="font-semibold">
                {rooms.length}
              </span>
            </div>

            <div className="flex items-center justify-between rounded-lg bg-slate-50 p-3">
              <span className="text-sm text-slate-600">
                Available Resources
              </span>

              <span className="font-semibold">
                {
                  rooms.filter(
                    (room) => room.available
                  ).length
                }
              </span>
            </div>

            <div className="flex items-center justify-between rounded-lg bg-slate-50 p-3">
              <span className="text-sm text-slate-600">
                Occupied Resources
              </span>

              <span className="font-semibold">
                {
                  rooms.filter(
                    (room) => !room.available
                  ).length
                }
              </span>
            </div>
          </div>

          <button
            onClick={runAllocation}
            disabled={loading}
            className="mt-6 w-full rounded-lg bg-slate-900 px-4 py-3 text-sm font-medium text-white transition hover:bg-slate-800 disabled:cursor-not-allowed disabled:opacity-60"
          >
            {loading
              ? "Running CSP..."
              : "Run AI Allocation"}
          </button>

          <div className="mt-5 rounded-lg border border-slate-200 p-4">
            <p className="text-xs font-semibold text-slate-700">
              AI Method
            </p>

            <ul className="mt-3 space-y-2 text-xs text-slate-500">
              <li>• Constraint Satisfaction Problem</li>
              <li>• MRV variable selection</li>
              <li>• Forward checking</li>
              <li>• Backtracking search</li>
            </ul>
          </div>
        </aside>
      </div>

      {allocationResult?.search_log?.length > 0 && (
        <section className="mt-6 rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
          <div>
            <h3 className="font-semibold">
              CSP Search Log
            </h3>

            <p className="mt-1 text-xs text-slate-500">
              Search decisions recorded by the allocation
              engine.
            </p>
          </div>

          <div className="mt-4 max-h-80 overflow-y-auto rounded-lg bg-slate-50 p-4">
            <div className="space-y-2 font-mono text-xs text-slate-600">
              {allocationResult.search_log.map(
                (event, index) => (
                  <div key={`${event}-${index}`}>
                    {index + 1}. {event}
                  </div>
                )
              )}
            </div>
          </div>
        </section>
      )}
    </div>
  )
}

export default Allocation